// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: fileexchange.proto

package FileExchange

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileExchange_Upload_FullMethodName = "/Dressy.FileExchange.FileExchange/Upload"
)

// FileExchangeClient is the client API for FileExchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileExchangeClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileData, UploadStatus], error)
}

type fileExchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewFileExchangeClient(cc grpc.ClientConnInterface) FileExchangeClient {
	return &fileExchangeClient{cc}
}

func (c *fileExchangeClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileData, UploadStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileExchange_ServiceDesc.Streams[0], FileExchange_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileData, UploadStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileExchange_UploadClient = grpc.ClientStreamingClient[FileData, UploadStatus]

// FileExchangeServer is the server API for FileExchange service.
// All implementations must embed UnimplementedFileExchangeServer
// for forward compatibility.
type FileExchangeServer interface {
	Upload(grpc.ClientStreamingServer[FileData, UploadStatus]) error
	mustEmbedUnimplementedFileExchangeServer()
}

// UnimplementedFileExchangeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileExchangeServer struct{}

func (UnimplementedFileExchangeServer) Upload(grpc.ClientStreamingServer[FileData, UploadStatus]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedFileExchangeServer) mustEmbedUnimplementedFileExchangeServer() {}
func (UnimplementedFileExchangeServer) testEmbeddedByValue()                      {}

// UnsafeFileExchangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileExchangeServer will
// result in compilation errors.
type UnsafeFileExchangeServer interface {
	mustEmbedUnimplementedFileExchangeServer()
}

func RegisterFileExchangeServer(s grpc.ServiceRegistrar, srv FileExchangeServer) {
	// If the following call pancis, it indicates UnimplementedFileExchangeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileExchange_ServiceDesc, srv)
}

func _FileExchange_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileExchangeServer).Upload(&grpc.GenericServerStream[FileData, UploadStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileExchange_UploadServer = grpc.ClientStreamingServer[FileData, UploadStatus]

// FileExchange_ServiceDesc is the grpc.ServiceDesc for FileExchange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileExchange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Dressy.FileExchange.FileExchange",
	HandlerType: (*FileExchangeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _FileExchange_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "fileexchange.proto",
}
